### PR TITLE
make TFT_Meters cpp compatible

### PR DESCRIPTION
**Pull request by LongLiveCHIEF**
When copy/pasting example to a platformio project, you get compiler errors with the `TFT_Meters` example due to missing declarations, (processing language hoists declarations, C++ does not)

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
related #632

**Comment by Bodmer** [comment]
I would think this applies to many more examples?  My understanding is that PlatformIO when configured for the Arduino environment handles the lack of early declarations.

**Comment by LongLiveCHIEF** [comment]
@Bodmer platformio just calls the compiler, and to my knowledge doesn't do any handling of declarations unless specified.

I wasn't entirely sure, so I did do a little digging, and early in their docs they have this section on [Converting Arduinio file to C++ manually](https://docs.platformio.org/en/latest/faq.html#convert-arduino-file-to-c-manually)

I thought it was strange that they used the word "manually" implying that there is an automatic feature somewhere... but I haven't been able to find it yet.

My process when installing libraries with PIO has been to declare them in the `platformio.ini`, and then go to the libraries tab and pick and choose an example and copy/paste it into one of my `src/*.cpp` files to test it. 

If I'm not missing something, that means that yes this problem would apply to virtually all of the examples in this library at the moment.

If you want, I can do more digging to confirm.

**Comment by Bodmer** [comment]
The library is targetted at the Arduino environment. The link to PlatformIO has been added on request of a user.

I suspect that users of PlatformIO are used to making declaration changes to examples to get them to compile. At least it seems that the main library does not create such errors!

I will mark as a potential future enhancement.

**Pull request closed without merging**
