### PR TITLE
Update TFT_eSPI_ESP32.h

### PR DESCRIPTION
**Pull request by hongthiet1994**
fix bug using tft parallel esp32 and uart  togerther

### CODE REVIEW

**Comment by hongthiet1994** [comment]
fix bug
TFT_eSPI_ESP32.h:353:22: error: expected ')' before numeric constant
TFT_eSPI_ESP32.h:353:22: error: expected initializer before numeric constant
TFT_eSPI_ESP32.h:353:22: error: expected ')' before numeric constant

when use tft parallel 8 bit together with uart freeRTOS ESP32

**Comment by Bodmer** [comment]
Looks like a nameing clash specific to this case and the ESP32.

I will think on this further as there are other processor code blocks that use that same name.

**Comment by Bodmer** [comment]
Please provide example code that demonstrates the problem. I am unable to reproduce this error.

**Comment by Bodmer** [comment]
I have search and replaced the names throughout the library so you should find you do not get the error anymore. Thanks for raising this.

**Pull request closed without merging**
