### PR TITLE
Add setLabelDatum

### PR DESCRIPTION
**Pull request by justcallmekoko**
Squashing was creating a bunch of problems so I just started from scratch

### CODE REVIEW

**Comment by Bodmer** [comment]
Sorry to hear about the difficilties
Looks good, thanks for persevering.

**Comment by justcallmekoko** [comment]
It's alright. I was expecting difficulties since this was my first ever contribution to someone else's repo. The difficulty was just trying to figure github out.

Glad to be able to contribute. Thanks again.

**Comment by Bodmer** [comment]
The [update broke this example](https://github.com/Bodmer/TFT_eSPI/tree/master/examples/320%20x%20240/Keypad_240x320). Can you check this and update so the example works.

**Comment by justcallmekoko** [comment]
Yup I will work it out

**Comment by Bodmer** [comment]
The button datum must always be with respect to the midle of the button otherwise legacy sketches will be broken so the correct lines are:
```
    _gfx->drawString(_label, _x1 + (_w/2) + _xd, _y1 + (_h/2) + _yd);
  else
    _gfx->drawString(long_name, _x1 + (_w/2) + _xd, _y1 + (_h/2) + _yd);
```
Note w/2
Also, so the delta y must be initialised to -4 in the constructor so legacy sketches will run without changes:
```
  _yd        = -4;
```

**Comment by Bodmer** [comment]
Just noticed the setLabelDatum function needs to be added to the keywords.txt file so it is highlighted in sketches.

**Comment by justcallmekoko** [comment]
I made the changes but I just read your suggestions. I did something similar with the `-4`
`_gfx->drawString(_label, _x1 + (_w/2) + _xd, _y1 + (_h/2) - 4 + _yd);`
It should do the same thing.

I did happen to update keywords with setLabelDatum

**Pull request merged**
