### PR TITLE
Added ST7796-Parallel-ESP32 User Setup header file

### PR DESCRIPTION
**Pull request by briankdlee**
I added ST7796-Parallel-ESP32 User Setup header file.

You can see the product desctiption at
http://www.lcdwiki.com/3.95inch_Arduino_Display-UNO

This file is similar to Setup14_ILI9341_Parallel.h

Please check it out.
Thanks in advance.

### CODE REVIEW

**Comment by Bodmer** [comment]
It is expected that users adapt the existing setups because of the high number or processor, pin and display combinations. There is a new "Discussions" section so I will create a new topic heading so users can post compatible display and setup file information.

**Comment by Bodmer** [comment]
[See new discussion area here](https://github.com/Bodmer/TFT_eSPI/discussions?discussions_q=category%3A%22Compatible+displays+and+setup+files%22).

**Comment by briankdlee** [comment]
@Bodmer I understand what you said. The more setup files, the harder to maintain. I don't care you don't accept my pull request. I'll wait your new topic.

**Comment by Bodmer** [comment]
I have setup [the topic here](https://github.com/Bodmer/TFT_eSPI/discussions?discussions_q=category%3A%22Compatible+displays+and+setup+files%22). You contribution will be welcome.

**Pull request closed without merging**
