### PR TITLE
160x80 bgr

### PR DESCRIPTION
**Pull request by tablatronix**
Support for unknown (ebay) chinese 160x80 BGR Inverted display modules, greentab.

### CODE REVIEW

**Comment by tablatronix** [comment]
7e4ebf4a-6a4c-4ee0-925c-823c86093170
5327cc46-232e-41f9-9339-a41c7a9497c9

**Comment by Bodmer** [comment]
Thanks for your input. Your setup changes look OK.  I will run some tests on my existing displays to check ther are no conflicts.

**Comment by tablatronix** [comment]
Yeah I was not sure the best naming convention to go with, it seems refactoring color mode and offsets just for a few displays that might be outliers is not worth it at this time.

Also this differs from adafruits versions in color mode and invert, and offsets.

**Comment by pteal** [comment]
I was able to use tablatronix's changes to get my 160x80 display up and running as well.  Thank you for your contribution.

**Comment by Bodmer** [comment]
I have one of these displays now and so will look at you pull request, thanks.

**Comment by tablatronix** [comment]
I did not add an example nor a config file. I might add one

**Comment by jirmjos** [comment]
Hi all !
Any news about when this commit changes for ST7735 80x160 displays that seems are working is avaible from master brach?.

Thanks so much to Bodmer and all people that are colaborate on this awesome library !

**Comment by Bodmer** [comment]
Thanks for the reminder on this. I have merged the update.

**Comment by jirmjos** [comment]
You r wellcome. Thanks to you !

**Pull request merged**
