### PR TITLE
Added support for M5Stack

### PR DESCRIPTION
**Pull request by tonywestonuk**
Added support for M5Stack - http://www.m5stack.com/

Involved changing the rotations, screen resolution (320x240 rather than 240x320), and adding a LCD LED control

### CODE REVIEW

**Comment by tonywestonuk** [comment]
This was a copy/paste/modify from the ili9341 driver. It works ok, though maybe it would be nicer in future to be able to carry on using the stock ILI9341 driver, but be able to include additional configs for different types of LCD that uses this?  Otherwise will end up with lots of duplication.

**Comment by Bodmer** [comment]
You can include tft.setRotation(1) or tft.setRotation(1) in the sketch setup to swap to landscape orientation so it is not clear to me why new driver files would be needed.

**Comment by tonywestonuk** [comment]
Its easier if I show you - Screen shots attached with stock driver - The first 3 are different rotations, 0 , 1 ,2 - The rotation rotates the image in the 240x320 resolution, not the viewport itself.  Changing the resolution to 320x240 in Defines.h fixes this.

The final image is what the stock rotations.h does - everything is reversed! - like a mirror - regardless of what rotation is set.
img_5429
img_5426
img_5427
img_5428

**Comment by tonywestonuk** [comment]
img_5431

**Comment by reaper7** [comment]
yes, it's true,  everything is mirrored on all available rotations.
what about new(additional) rotations for m5stack?

TFT_eSPI\TFT_Drivers\ILI9341_Rotation.h
line 4 from:
```
rotation = m % 8; // Limit the range of values to 0-7
```
to:
```
rotation = m % 12; // Limit the range of values to 0-7
```
and new cases:
```
  // These next rotations are for m5stack
    case 8:
      writedata(TFT_MAD_MX | TFT_MAD_MY | TFT_MAD_BGR);
      _width  = _height_orig;
      _height = _width_orig;
      break;
    case 9:
      writedata(TFT_MAD_MV | TFT_MAD_MX | TFT_MAD_BGR);
      _width  = _width_orig;
      _height = _height_orig;
      break;
    case 10:
      writedata(TFT_MAD_BGR);
      _width  = _height_orig;
      _height = _width_orig;
      break;
    case 11:
      writedata(TFT_MAD_MY | TFT_MAD_MV | TFT_MAD_BGR);
      _width  = _width_orig;
      _height = _height_orig;
      break;
```

**Comment by Bodmer** [comment]
Thanks I will add support for the M5Stack. I will consider further how to do this whilst making sure existing sketches run without modification.

**Comment by reaper7** [comment]
so...second option (without additional cases)
but currently macro name for M5Stack is not entirely compatible with arduino standard:
https://github.com/m5stack/M5Stack/issues/41
```
#ifdef ARDUINO_M5Stack-Core-ESP32 //orientations 0-3 for M5Stack (as above)
case 0:
.
.
.
#else                                                    //existing orientations 0-3 (from current code)
case 0:
.
.
.
#endif
```

**Comment by Bodmer** [comment]
I have added support for the M5Stack but cannot test it. I have ordered an M5Stack to play with!

Rotation 0 is portrait mode so you will need to call setRotation(1) in your sketch to orient the display.

Thanks for your input to this change.

**Comment by reaper7** [comment]
I tested almost all examples, for me rotations 0-3 works very well!

Two comments:
1. about rotations 4-7 (I do not use them but I checked, please see if this is how it should be):
- 4 looks like 2
- 5 looks like 0 but mirrored and probably swapped W with H
- 6 looks like 2 but mirrored
- 7 looks like 3 but mirrored

2. keypad example (yes, I know that m5stack does not have touch ;) ) -> compilation error: SPIFFS not declared 
it seems that esp32 needs in this example additional #include "SPIFFS.h"

**Comment by tonywestonuk** [comment]
Closing pull request as no longer needed.  Thank you  Bodmer / Reaper7 :-)

**Comment by Bodmer** [comment]
Mirrored rotations 4-7 were wrong so I have corrected these.

**Pull request closed without merging**
