### PR TITLE
Add 4bit images to sprites, with an example and a tool to produce the images from bmp files.

### PR DESCRIPTION
**Pull request by kamorris**

### CODE REVIEW

**Comment by kamorris** [comment]
Hi, I wanted to add images to my sprites, but keep them small (4bit). Please take a look.

Thanks,
  Kate

**Comment by Bodmer** [comment]
Thanks, I will download and run some tests.

**Comment by Bodmer** [comment]
I have run update. The only issue I found was with the example which contains 2 ino files. I suspect one needs to be deleted.

**Comment by kamorris** [comment]
I deleted the extraneous .ino file.  Sorry about that.

**Comment by Bodmer** [comment]
Merged thanks.

**Comment by Bodmer** [comment]
A user wants to use the python script with an odd pixel count width but it appears the script only works with even widths, is this something you can help with, see #1632.

**Comment by kamorris** [comment]
I’ll take a look. 

   Kate Morris

**Pull request merged**
