### PR TITLE
Increase support for LE501X series chips and Microduino family

### PR DESCRIPTION
**Pull request by wasdpkj**
Increase support for LE501X series chips and Microduino family

### CODE REVIEW

**Comment by Bodmer** [comment]
Provide web links to the boards please.

**Comment by wasdpkj** [comment]
> 


Link Here：
https://gitee.com/wasdpkj/Linkedsemi_Arduino-IDE-Support

**Comment by Bodmer** [comment]
Please add links to the circuit board vendors, ie where assembled processors boards can be purchased.

**Comment by wasdpkj** [comment]
Okay, I see what you mean. But Linkedsemi's development board is not currently available for sale.
If you need module samples, you can send your receiving information to my email: kjpan@linkedsemi.com
I am the author of the Arduino Support Package for LE5010.
I can give you some additional LE5010 information:

- Official website introduction:  https://www.linkedsemi.com/products/ble-5010-chip.html

- Some of the documentation:   https://ls-doc.readthedocs.io/zh_CN/latest/src/le5010.html
- Evaluation Boards:  https://ls-doc.readthedocs.io/zh_CN/latest/src/le5010/evb.html

- Arduino support package Update Address:  https://gitee.com/wasdpkj/Linkedsemi_Arduino-IDE-Support

- Module information (to be updated): https://docs.linkedsemi.com/doc?id=957

- [LE5010_5110_brief](https://www.linkedsemi.com/docs/docs/ble/LE5010/LE5010_5110_brief_EN_V1.4.pdf)
- [LE5010_5110_DATASHEET](https://www.linkedsemi.com/docs/docs/ble/LE5010/LE5010_5110_DATASHEET_V1.9%20.pdf)

I would love to be able to incorporate the cost into this project, thank you.

**Comment by wasdpkj** [comment]
May I ask if this part of the code can be merged? What more information do I need to provide to you?

**Comment by Bodmer** [comment]
I suggest you clone the library and adapt for your board users. I don't have time to support a new processor variant or board and I would not be able to support users who raised issues here.

**Pull request closed without merging**
