### PR TITLE
Allow externally defined configuration rather than User_Setup.h modifications in library

### PR DESCRIPTION
**Pull request by atanisoft**
Adding ability to load settings from the calling program rather than modifying the library for each project that uses it. This is mostly for PlatformIO IDE which manages the libraries differently than Adruino IDE.

### CODE REVIEW

**Comment by Bodmer** [comment]
Great! I have just loaded PlatformIO to try and I can see why this change is neat, simple and a useful update.

Thanks.

**Comment by atanisoft** [comment]
Thanks! I was running in circles for a bit trying to get a display working on an esp32 and it wouldn't work. I modified the library to try a few options before arriving at this one.

**Comment by Bodmer** [comment]
I will make some changes to make it clear which user setups are for the ESP32.

**Comment by beegee-tokyo** [comment]
Didn't work for me.
I changed **`Update User_Setup_Select.h`** as shown in the pull request.
Then I tried to define the display settings in my include file just before I include **`TFT_eSPI.h`**:
```cpp
...
#define USER_SETUP_LOADED 1
#define ILI9163_DRIVER
#define TFT_WIDTH  128
#define TFT_HEIGHT 160
#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS    5  // Chip select control pin
#define TFT_DC    19  // Data Command control pin
#define TFT_RST  -1  // Set TFT_RST to -1 if display RESET is connected to ESP32 board RST
#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define SPI_FREQUENCY  27000000 // Actually sets it to 26.67MHz = 80/3
#include "TFT_eSPI.h"
...
```
But the user settings are not used. What am I doing wrong?
PlatformIO version: Home 0.5.3·Core 3.5.0rc10
ESP32 platform: Espressif 32 (Stage) version c9fe5b9
Atom version 1.23.1 x64

**Comment by atanisoft** [comment]
Add them to your platformio.ini file via build_flags as -DTFT_RST=-1 etc.

**Comment by beegee-tokyo** [comment]
Thank you! Now it works.

**Pull request merged**
