### PR TITLE
added color maps and examples

### PR DESCRIPTION
**Pull request by kamorris**
Added color map for 4 bit sprites.

Does not include pushing images to the sprites.

Three examples: scrolling with color maps, transparent sprites using color maps, and moving a sprite around the screen.

### CODE REVIEW

**Comment by Bodmer** [comment]
This is great. Thank you. I have tested and reviewed the code and you have done a good job of maintaining the style of the code and I have not spotted any issues with the code.  I have a few suggested changes, I can pull the changes into a branch and make the changes myself if you wish.

1. I prefer not to include Serial.print debug messages in case there serial port has been re-purposed. I think they are useful though and I ought to start adding more in future, so a #ifdef TFT_eSPI_DEBUG condition is needed.
2. The transparent sprite demo example should use font 4 for the final timing output value.
3. After some mental deliberation on the new function names I have come up with the following alternatives/additions (the internal library variable names do not need to change):
```
void     createPalette(uint16_t *palette, uint8_t colors = 16); // Color count default is 16

uint16_t setPaletteColor(uint8_t index); // To change a single indexed color

uint16_t getPaletteColor(uint8_t index); // To get a palette color from the pixel value

uint16_t readPixelValue(int32_t x, int32_t y); // To fetch the pixel value (aka palette index)
```

Let me know if you wish me to make these changes or are willing to do them yourself to your fork.

**Comment by kamorris** [comment]
Thanks, sounds good.  I will make the updates in my branch and push changes this weekend.

Agreed on the font issue.  I am using this library for a game I’m writing for the badge my son and I created for defcon last year, and I have memory constraints (so my user-setup restricts the fonts).  I need to go back to working on the hardware side of that now that I have a working library.

I may yet implement code to push a palette-based image, since one of the games on last year’s badge wants a grey-scale image (will let you know if I get to that).

**Comment by Bodmer** [comment]
To correct one function prototype:
```
uint16_t setPaletteColor(uint16_t color, uint8_t index); // To change a single indexed color
```
I would also like to add a default palette by some means but have not thought further.

The createPalette(uint16_t *palette, uint8_t colors = 16); function should check that it is not being passed a nullptr. e.g. if (colorMap == nullptr) return; This stops error states from developing.

**Comment by kamorris** [comment]
I pushed those changes to github (and the ones from the previous email).

I agree that it’d be good to have a default palette - the one from the examples might be a good starting point - but I didn’t take the idea further than that.

**Comment by Bodmer** [comment]
That was quick! Merged. Thanks. Will update if required over the next few days if I spot anything that needs tweaking.

**Comment by Bodmer** [comment]
I have added a default FLASH based palette and a new read PROGMEM createPalette() function to handle this palette. This is used in the renamed "Transparent_Sprite_Demo_4bit" example.

4 bit examples has been edited for consistency and renamed. Some new default colours have been defined for use in a palette.

I used this to conveniently generate a greyscale palette for the "Transparent_Sprite_Demo_4bit"  example:
```
  // Change the palette to a 16 bit grey scale colour
  for (uint8_t i = 0; i < 16; i++) {
    // (i*16+i) produces a value in range 0-255 for the RGB colours
    //                                   Red    Green    Blue
    spr.setPaletteColor(i, tft.color565(i*16+i, i*16+i, i*16+i));
  }
```
Refactoring is now complete and the library has been raised to version 2.0.0 - hope no new bugs were introduced!

Thanks again for you input.

**Comment by kamorris** [comment]
Thanks - sounds good!

  Kate

**Pull request merged**
