### PR TITLE
ESP-IDF compatibility

### PR DESCRIPTION
**Pull request by dracir9**
Added the necessary files for the library to be added as a component in an ESP-IDF project.

The library can be configure through `idf.py menuconfig`

Should not interfere with the already existing features.

### CODE REVIEW

**Comment by Bodmer** [comment]
I have not used the IDF flow myself so will not be able to test or support users, so that makes me wonder if this is going to cause me grief later...

Please describe what testing you have done and provide links to IDF user guides for Arduino libraries.

**Comment by dracir9** [comment]
What I've done includes:
- Add `CMakeLists.txt` to allow the ESP-IDF to recognize the component
- Add `Kconfig` to create a graphical configuration menu which can be accessed by running `idf.py menuconfig` in your project
- Add a translation header which converts from the defines created by the IDF to the defines used in the library

The "menuconfig" app creates a header with a bunch of preprocessor definitions (`#define`) in the format `CONFIG_settingName`. This header is then included accros all the project files. What I'm doing in [TFT_config.h](https://github.com/Bodmer/TFT_eSPI/pull/1770/files#diff-29dd48ac8a244001b47c811443cf9834764783742599f7cf109d0863b562c9a3) is to translate the `CONFIG_something` into the define used in this library.
For example:
If `CONFIG_TFT_ILI9341_DRIVER` is defined I define `ILI9341_DRIVER`.

I've been using the modified version of this library on one of my [projects](https://github.com/dracir9/3DPrinterScreen/tree/dev_branch) so it has some testing and works without problems. My setup is an ESP32-Wroover-e Rev3 with an ILI9488 with SPI communication.

You still need the arduino core to use the library and no changes to important parts of the library have been made. From the maintenance point of view nothig should change as the arduino core handles most of the translation to the low level ESP-IDF functions.

Steps to use:
1. Install [ESP-IDF toolchain](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html#installation-step-by-step). The easiest way is to use [VS Code](https://code.visualstudio.com) and the [ESP-IDF extension](https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension) which handles most of the work automatically. Make sure to install version V4.4. From now on I'll asume that VS Code is being used.
2. Once ESP-IDF is installed open VS Code and press `F1`. Type `ESP-IDF: New Project`. Hit enter.
3. Enter your project name, directory and board (if not sure choose `ESP32 chip (via ESP-PROG)`). If your board is conected choose serial port. Leave ESP-IDF component directory blank and press `Choose Template`.
4. In the dropdown choose Extension and select `arduino-as-component`. (This is not mandatory. You can try other templates if you want). This will create a blank project with a simple main source file in the "main" folder.
5. Now we have to add arduino to your project. You can find the complete documentation [here](https://github.com/espressif/arduino-esp32) and [here](https://docs.espressif.com/projects/arduino-esp32/en/latest/esp-idf_component.html). I'll list two methods that I use most of the time:
5.1. Press `F1` and type `ESP-IDF: Add Arduino ESP32 as ESP-IDF Component`. This will automatically download and install the latest code from the [arduino esp-32 repository](https://github.com/espressif/arduino-esp32). This is the easiest method but as it uses the latest code it may introduce compilation errors.
5.2. Go to the [arduino esp-32 repository](https://github.com/espressif/arduino-esp32/releases) release page. Choose a version and find its "Assets" section. Download the source code file into "project directory/components". Extract the compressed file. This will create a folder called `arduino-esp32-2.x.x`. Rename it to `arduino`. This method is slightly more complex but ensures you choose a stable version.
6. Download the TFT_eSPI library into the components folder
7. Now open VS Code and load your project folder. Press `F1` and type `ESP-IDF: SDK Configuration editor (menuconfig)`. Alternatively press `Ctrl+E`, `G` or press the gear button in the bottom left corner.
8. This will open the project configuration menu. Navigate to the TFT_eSPI section and configure the library (TFT driver, pins, fonts, etc.).
9. Press `F1` and type `ESP-IDF: Build your project`. Alternatively press `Ctrl+E`, `B` or click the build button in the bottom left corner.
10. Choose your port by typing `ESP-IDF: Select port to use` or with the button in the bottom left.
11. Upload your code with the lightning button in the bottom toolbar.
12. Enjoy!

**PD**
I decided to PR to help expand your library use cases. If you think that this would be too hard to maintain feel free to reject the PR

**Comment by Bodmer** [comment]
Thanks for the infomation. I will copy the instructions into the info in the tools folder.

**Comment by troyaduncan** [comment]
Range values in kconfig need to be updated to support ESP32-S2. Currently, range is -1 32. 
I am using the following pins on a ESP32-S2 dev kit : 
#define TFT_MISO	37 	//19
#define TFT_MOSI 	35	//23
#define TFT_SCLK 	36	//18
#define TFT_CS   	34	//15

**Comment by Bodmer** [comment]
OK, I guess maximum should be 48 for future support of S3. @dracir9 does this need to be a hard coded value?

**Comment by dracir9** [comment]
Increasing the range would work but will allow users to enter invalid values in some cases.
I've made a fix for this, only I haven't used pr quite often and I'm not sure if I can add the modified files here. Can I? How?

**Comment by Bodmer** [comment]
Thanks PR merged.

**Pull request merged**
